
os: linux
dist: focal

vm:
  size: 2x-large

language: go
go:
- 1.18.x

addons:
  apt:
    packages:
    - rpm
go_import_path: github.com/nats-io/nats-server

script: go test -race -v -run=TestJetStreamJWTMove ./server -count=100 -vet=off -failfast -timeout=40m

deploy:
  provider: script
  cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: ($TRAVIS_GO_VERSION =~ 1.18) && ($TEST_SUITE = "compile")
